### ISSUE TITLE
Useful package, please document it!

### ISSUE THREAD

**Issue by niftylettuce** [ryanwild/nunjucks-highlight.js#1]
Update the Readme to show usage 👍

**Comment by ryanwild** [comment]
Hey sorry for the delay I have not updated this package in quite a while I am busy going through your PR now... Thanks

**Comment by niftylettuce** [comment]
Ryan can you please accept my pull request or give me collaborator status on this repository?

If you give me collaborator status, please add me to the NPM package with `npm add-owner`.  My NPM username is the same as my GitHub.

**Comment by ryanwild** [comment]
@niftylettuce sure happy to add you as a collaborator, I checked out your PR then ran the tests on my machine and could not get them to pass... Any suggestions?

**Comment by niftylettuce** [comment]
fixed!
